name: GoldenBomb
main: org.eldrygo.GoldenBomb.GoldenBomb
version: 0.0.10
authors:
  - Drygo
  - Turtle Club
api-version: 1.20
commands:
  goldenbomb:
    aliases:
      - gb
    description: "Main plugin command."
permissions:
  goldenbomb.admin:
    description: "Plugin administration command permission."