name: rTNTTag
main: org.eldrygo.RTNTTag.RTNTTag
version: 0.0.03
api-version: 1.20
authors:
  - Drygo
  - Turtle Club
softdepend:
  - PlaceholderAPI
  - xBossBar
commands:
  rtnttag:
    description: "rTNTTag plugin main command."
permissions:
  rtnttag.admin:
    description: "Plugin administration command permission."
    default: false